src/cbv_app/urls.py
from django.urls import path, include
from cbv_app import views

app_name = 'cbv_app'

urlpatterns = [
    path('', views.SchoolListView.as_view(),name='list'),
    path('<int:pk>/', views.SchoolDetailView.as_view(), name='detail'),
]
# ?P<pk>[-\w]+ used in django 1.11 and above instead of <int:pk>

src/djangocbv/urls.py
from django.contrib import admin
from django.urls import path, include

from cbv_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', views.index, name='index'),
    # path('', views.CVView.as_view(), name='my_cbv'),
    path('', views.IndexView.as_view(), name='my_cbv'),
    path('cbv_app/', include('cbv_app.urls', namespace='cbv_app')),
]

src/cbv_app/models.py
from django.db import models

# Create your models here.

class School(models.Model):

    name = models.CharField(max_length=256)
    principal = models.CharField(max_length=256)
    location = models.CharField(max_length=256)

    def __str__(self):

        return self.name

class Student(models.Model):

    name = models.CharField(max_length=256)
    age = models.PositiveIntegerField()
    school = models.ForeignKey(School, related_name='students', on_delete=models.DO_NOTHING)

    def __str__(self):

        return self.name

src/cbv_app/views.py
from django.shortcuts import render
from django.views.generic import View, TemplateView, ListView, DetailView
from django.http import HttpResponse
from . import models

class CVView(View):

    def get(self, request):
        return HttpResponse("WE ARE USING CLASS BASED VIEWS NOW")

class IndexView(TemplateView):

    template_name = 'index.html'

    def get_context_data(self, **kwargs):

        context = super().get_context_data(**kwargs)
        context['my_key'] = 'I am the value of that key'
        return context
         


def index(request):

    context = {}
    return render(request, 'index.html', context)

class SchoolListView(ListView):

    context_object_name = 'schools'
    model = models.School


class SchoolDetailView(DetailView):

    context_object_name = 'school_detail'
    model = models.School
    template_name = 'cbv_app/school_detail.html'

src/cbv_app/templates/cbv_app/cbv_app_base.html
<!DOCTYPE html>
<html>
<head>
    <title>Base</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
</head>
<body>

    <nav class="navbar navbar-default navbar-default navbar-static-top">
        <div class="container">
            <ul class="nav navbar-nav">
                <li><a class="navbar-brand" href="{% url 'cbv_app:list' %}">Schools</a></li>
                <li><a class="navbar-admin" href="{% url 'admin:index' %}">Admin</a></li>
                <li><a class="navbar-register" href=""></a></li>
            </ul>
        </div>
        </nav> 

    <div class="container">
        {% block body_block %}
        {% endblock %}
    </div>
</body>
</html>

src/cbv_app/templates/cbv_app/school_detail.html
{% extends 'cbv_app/cbv_app_base.html' %}

{% block body_block %}

<div class="jumbotron">
    <h1>This is a school detail page </h1>
    <h2>School Details:</h2>
    <p>Name: {{ school_detail.name }}</p>
    <p>Principal: {{ school_detail.principal }}</p>
    <p>Location: {{ school_detail.location }}</p>

    <!-- <h3>Students:</h3>

    {% for student in school_detail.students.all %}
    <p>{{ student.name }} is {{student.age}} years old.</p>
    {% endfor %} -->
</div>


{% endblock %}

src/cbv_app/templates/cbv_app/school_list.html
{% extends 'cbv_app/cbv_app_base.html' %}

{% block body_block %}

<ol>
    <h1>This is a school list page </h1>
    {% for school in schools %}    
    <h2><li><a href="{{ school.id }}">{{school.name}}</a></li></h2>
    {% endfor %}
</ol>

{% endblock %}

src/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <title>Base</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
</head>
<body>

    <nav class="navbar navbar-default navbar-default navbar-static-top">
        <div class="container">
            <ul class="nav navbar-nav">
                <li><a class="navbar-brand" href="{% url 'cbv_app:list' %}">Schools</a></li>
                <li><a class="navbar-admin" href="{% url 'admin:index' %}">Admin</a></li>
                <li><a class="navbar-register" href=""></a></li>
            </ul>
        </div>
        </nav> 

    <div class="container">
        {% block body_block %}
        {% endblock %}
    </div>
</body>
</html>

src/templates/index.html
{% extends 'base.html' %}

{% block body_block %}

    <div class="jumbotron">

        <h1>This is my Mike's page!</h1>
    </div>

{% endblock %}